"""Exact Source inverses for the prospective FRONT quick dispatcher only."""
import hashlib
from pathlib import Path

_PAIRS = {
    "quick": [
        "35808d483b82a4da1cd9c22e4a9ef967986dd7ab4ede448f8cd98db9d0c3b25c",
        "70d0fbed289b3f7362f0334717ec5a9f61d7575d6dcf125b87782f9ee8315e05",
        [
            [
                "from . import rapid_rolling_capture as rolling\nfrom . import rapid_site_admission as receipts\nfrom . import rapid_slot_chunks as geometry\n\nCAPSULE_TYPE = \"qcsd-prospective-direct-quick-launch-profile-v1\"\nMODE_CAPSULE_TYPE = \"qcsd-prospective-direct-quick-launch-profile-v2\"\nPLAN_TYPE = \"qcsd-prospective-direct-quick-formal-plan-v1\"\nFIELD = \"direct_quick_launch_profile\"\nCONTRACT = \"current-material-bindings-complete-graphs-fixed-settings-full-deep-50x5x64-v1\"\n",
                "from . import rapid_rolling_capture as rolling\nfrom . import rapid_site_admission as receipts\nfrom . import rapid_slot_chunks as geometry\nfrom . import rapid_front_quick_profile as front_quick\n\nCAPSULE_TYPE = \"qcsd-prospective-direct-quick-launch-profile-v1\"\nMODE_CAPSULE_TYPE = \"qcsd-prospective-direct-quick-launch-profile-v2\"\nFRONT_CAPSULE_TYPE = front_quick.PROFILE_TYPE\nPLAN_TYPE = \"qcsd-prospective-direct-quick-formal-plan-v1\"\nFIELD = \"direct_quick_launch_profile\"\nCONTRACT = \"current-material-bindings-complete-graphs-fixed-settings-full-deep-50x5x64-v1\"\n"
            ],
            [
                "PLAN_FIELDS = {\"study_version\", \"cohort_generation\", \"bindings\", \"runtime\", \"runtime_artifacts\", \"acquisition_provenance_sha256\",\n    \"qualification_spec_sha256\", \"data_role\", \"capture_limits\", \"application_body_identity_policy\",\n    \"qualification_delivery_compatibility\", \"tamaraw_configuration_policy\", \"buflo_duration_policy\", \"static_capture_amendment\",\n    \"ordinary_capture_contract\"}\n\n\ndef is_payload(value):\n",
                "PLAN_FIELDS = {\"study_version\", \"cohort_generation\", \"bindings\", \"runtime\", \"runtime_artifacts\", \"acquisition_provenance_sha256\",\n    \"qualification_spec_sha256\", \"data_role\", \"capture_limits\", \"application_body_identity_policy\",\n    \"qualification_delivery_compatibility\", \"tamaraw_configuration_policy\", \"buflo_duration_policy\", \"static_capture_amendment\",\n    \"ordinary_capture_contract\", \"front_configuration_policy\", \"front_incoming_credit_acceptance_policy\"}\n\n\ndef is_payload(value):\n"
            ],
            [
                "\n\ndef is_profile(value):\n    return isinstance(value, dict) and value.get(\"artifact_type\") in {CAPSULE_TYPE, MODE_CAPSULE_TYPE}\n\n\ndef is_plan(path):\n",
                "\n\ndef is_profile(value):\n    return isinstance(value, dict) and value.get(\"artifact_type\") in {CAPSULE_TYPE, MODE_CAPSULE_TYPE, FRONT_CAPSULE_TYPE}\n\n\ndef is_plan(path):\n"
            ],
            [
                "    return path\n\n\ndef _runtime_once(spec, canonical_ref):\n    \"\"\"Check the current closed installation, without reopening its ancestors.\"\"\"\n    from . import rapid_rolling_readiness as evidence\n    canonical_path = _open(canonical_ref)\n",
                "    return path\n\n\ndef _runtime_once(spec, canonical_ref, *, front=False):\n    \"\"\"Check the current closed installation, without reopening its ancestors.\"\"\"\n    from . import rapid_rolling_readiness as evidence\n    canonical_path = _open(canonical_ref)\n"
            ],
            [
                "    root = canonical_path.parent\n    source = lanes._load(lanes._read(spec.source_manifest))\n    client_sha = lanes._sha(lanes._read(spec.client_binary))\n    if (canonical.get(\"installed_byte_verification_completed\") is not True\n        or canonical.get(\"scientific_credit\") is not False\n        or canonical.get(\"collection_image_digest\") != spec.collection_image_digest\n        or canonical.get(\"source\") != source\n        or source.get(\"lab_dirty\") is not False or source.get(\"neqo_dirty\") is not False\n        or source.get(\"lab_patch_sha256\") != EMPTY_SHA256 or source.get(\"neqo_patch_sha256\") != EMPTY_SHA256\n        or source.get(\"neqo_commit\") != NATIVE or source.get(\"neqo_pinned_commit\") != NATIVE\n        or canonical.get(\"installed_client_sha256\") != client_sha\n        or canonical.get(\"exported_source_manifest_sha256\") != lanes._sha(lanes._read(spec.source_manifest))):\n        raise ValueError(\"quick profile requires the actual current Native818 installation\")\n",
                "    root = canonical_path.parent\n    source = lanes._load(lanes._read(spec.source_manifest))\n    client_sha = lanes._sha(lanes._read(spec.client_binary))\n    expected_native = front_quick.NATIVE if front else NATIVE\n    if (canonical.get(\"installed_byte_verification_completed\") is not True\n        or canonical.get(\"scientific_credit\") is not False\n        or canonical.get(\"collection_image_digest\") != spec.collection_image_digest\n        or canonical.get(\"source\") != source\n        or source.get(\"lab_dirty\") is not False or source.get(\"neqo_dirty\") is not False\n        or source.get(\"lab_patch_sha256\") != EMPTY_SHA256 or source.get(\"neqo_patch_sha256\") != EMPTY_SHA256\n        or source.get(\"neqo_commit\") != expected_native or source.get(\"neqo_pinned_commit\") != expected_native\n        or canonical.get(\"installed_client_sha256\") != client_sha\n        or canonical.get(\"exported_source_manifest_sha256\") != lanes._sha(lanes._read(spec.source_manifest))):\n        raise ValueError(\"quick profile requires the actual current Native818 installation\")\n"
            ],
            [
                "\ndef _traffic_files(seed):\n    from . import rapid_capture_traffic as traffic\n    return traffic.files(traffic.policy(seed.get(traffic.FIELD)))\n\n\n",
                "\ndef _traffic_files(seed):\n    from . import rapid_capture_traffic as traffic\n    if front_quick.selected(seed, \"front\"):\n        return traffic.plan_files(seed)\n    return traffic.files(traffic.policy(seed.get(traffic.FIELD)))\n\n\n"
            ],
            [
                "    execution, clean = Path(recipe[\"execution_root\"]), Path(recipe[\"clean_runtime_root\"])\n    campaign_path = evidence._child(execution, campaign.get(\"campaign_relative\"))\n    files.add(_open({\"path\": str(campaign_path), \"sha256\": campaign.get(\"campaign_sha256\")}, context))\n    declared = Path(deep.get(\"root\", \"\"))\n    if (type(campaign.get(\"visits\")) is not int or campaign[\"visits\"] != 1\n        or deep.get(\"name\") != campaign.get(\"name\") or deep.get(\"purpose\") != \"smoke\"\n",
                "    execution, clean = Path(recipe[\"execution_root\"]), Path(recipe[\"clean_runtime_root\"])\n    campaign_path = evidence._child(execution, campaign.get(\"campaign_relative\"))\n    files.add(_open({\"path\": str(campaign_path), \"sha256\": campaign.get(\"campaign_sha256\")}, context))\n    if front_quick.selected(seed, mode):\n        import yaml\n        front_quick.validate_campaign(yaml.safe_load(lanes._read(campaign_path)))\n    declared = Path(deep.get(\"root\", \"\"))\n    if (type(campaign.get(\"visits\")) is not int or campaign[\"visits\"] != 1\n        or deep.get(\"name\") != campaign.get(\"name\") or deep.get(\"purpose\") != \"smoke\"\n"
            ],
            [
                "\ndef _mode_selection(seed, mode, context=None):\n    \"\"\"Reopen one original ready mode's direct records, without ancestor audits.\"\"\"\n    rows = [row for row in seed[\"lanes\"] if row[\"mode\"] == mode]\n    reference = seed.get(\"readiness\", {}).get(mode)\n    if (mode not in rolling.plan.MODES or not rows or any(row.get(\"role\") != \"formal\" for row in rows)\n",
                "\ndef _mode_selection(seed, mode, context=None):\n    \"\"\"Reopen one original ready mode's direct records, without ancestor audits.\"\"\"\n    fixed_front = front_quick.selected(seed, mode)\n    expected_native = front_quick.NATIVE if fixed_front else NATIVE\n    rows = [row for row in seed[\"lanes\"] if row[\"mode\"] == mode]\n    reference = seed.get(\"readiness\", {}).get(mode)\n    if (mode not in rolling.plan.MODES or not rows or any(row.get(\"role\") != \"formal\" for row in rows)\n"
            ],
            [
                "        or deep.get(\"plan_sha256\") != reference[\"plan\"][\"sha256\"]\n        or deep.get(\"workload_sha256\") not in {site[\"workload_sha256\"] for site in seed[\"sites\"]}\n        or any(deep.get(\"source\", {}).get(key) != source.get(key) for key in identity)\n        or source.get(\"neqo_commit\") != NATIVE or source.get(\"neqo_pinned_commit\") != NATIVE\n        or source.get(\"lab_dirty\") is not False or source.get(\"neqo_dirty\") is not False\n        or source.get(\"lab_patch_sha256\") != EMPTY_SHA256 or source.get(\"neqo_patch_sha256\") != EMPTY_SHA256\n        or recipe.get(\"expected_lab_commit\") != source.get(\"lab_commit\") or recipe.get(\"expected_native_commit\") != NATIVE\n        or recipe.get(\"traffic_hashes\") != {key: digest for key, (_, digest) in _traffic_files(seed).items()}\n        or recipe.get(\"capture_limits\") != {**seed.get(\"capture_limits\", {}), \"max_attempts\": 1}\n        or deep.get(\"application_body_identity_policy\") != seed.get(\"application_body_identity_policy\")\n        or mode == \"tamaraw\" and deep.get(\"tamaraw_configuration_policy\") != seed.get(\"tamaraw_configuration_policy\")):\n        raise ValueError(\"quick explicit mode differs from its genuine original Native/settings readiness\")\n    _mode_readiness_domain(seed, mode, reference, recipe, deep, source, files, context)\n    return {\"mode\": mode, \"readiness\": reference}, rows, files\n\n",
                "        or deep.get(\"plan_sha256\") != reference[\"plan\"][\"sha256\"]\n        or deep.get(\"workload_sha256\") not in {site[\"workload_sha256\"] for site in seed[\"sites\"]}\n        or any(deep.get(\"source\", {}).get(key) != source.get(key) for key in identity)\n        or source.get(\"neqo_commit\") != expected_native or source.get(\"neqo_pinned_commit\") != expected_native\n        or source.get(\"lab_dirty\") is not False or source.get(\"neqo_dirty\") is not False\n        or source.get(\"lab_patch_sha256\") != EMPTY_SHA256 or source.get(\"neqo_patch_sha256\") != EMPTY_SHA256\n        or recipe.get(\"expected_lab_commit\") != source.get(\"lab_commit\") or recipe.get(\"expected_native_commit\") != expected_native\n        or recipe.get(\"traffic_hashes\") != {key: digest for key, (_, digest) in _traffic_files(seed).items()}\n        or recipe.get(\"capture_limits\") != {**seed.get(\"capture_limits\", {}), \"max_attempts\": 1}\n        or deep.get(\"application_body_identity_policy\") != seed.get(\"application_body_identity_policy\")\n        or mode == \"tamaraw\" and deep.get(\"tamaraw_configuration_policy\") != seed.get(\"tamaraw_configuration_policy\")):\n        raise ValueError(\"quick explicit mode differs from its genuine original Native/settings readiness\")\n    if fixed_front:\n        front_quick.validate_readiness(seed, recipe, deep, source)\n    _mode_readiness_domain(seed, mode, reference, recipe, deep, source, files, context)\n    return {\"mode\": mode, \"readiness\": reference}, rows, files\n\n"
            ],
            [
                "    if is_plan(spec.plan_receipt):\n        raise ValueError(\"quick profile must start from an original qualified cohort plan\")\n    seed = lanes.plan_payload(lanes._read(spec.plan_receipt))\n    cohort_frame = lanes._load(lanes._read(spec.cohort))\n    cohort = receipts._unpack(lanes._read(spec.cohort), cohort_frame[\"receipt_type\"])\n    declared_ids = cohort.get(\"selected_candidate_ids\", [row[\"candidate_id\"] for row in cohort.get(\"decisions\", [])\n",
                "    if is_plan(spec.plan_receipt):\n        raise ValueError(\"quick profile must start from an original qualified cohort plan\")\n    seed = lanes.plan_payload(lanes._read(spec.plan_receipt))\n    fixed_front = front_quick.selected(seed, mode)\n    cohort_frame = lanes._load(lanes._read(spec.cohort))\n    cohort = receipts._unpack(lanes._read(spec.cohort), cohort_frame[\"receipt_type\"])\n    declared_ids = cohort.get(\"selected_candidate_ids\", [row[\"candidate_id\"] for row in cohort.get(\"decisions\", [])\n"
            ],
            [
                "    sites = tuple(site for site in sites if site.workload_id in selected)\n    if not 1 <= len(sites) <= 5:\n        raise ValueError(\"quick cohort requires one through five complete admitted sites\")\n    canonical, inventory_ref = _runtime_once(spec, canonical_ref)\n    files = {getattr(spec, name) for name in (\"cohort\", \"qualification_spec\", \"source_manifest\",\n        \"client_binary\", \"base_launcher\", \"host_launcher\")}\n    files.update({_open(canonical_ref), _open(inventory_ref), original.plan_receipt})\n",
                "    sites = tuple(site for site in sites if site.workload_id in selected)\n    if not 1 <= len(sites) <= 5:\n        raise ValueError(\"quick cohort requires one through five complete admitted sites\")\n    if fixed_front:\n        front_quick.validate_artifacts({key: spec.serializable()[key] for key in rolling.RUNTIME_FIELDS}, context=_context)\n        canonical, inventory_ref = _runtime_once(spec, canonical_ref, front=True)\n    else:\n        canonical, inventory_ref = _runtime_once(spec, canonical_ref)\n    files = {getattr(spec, name) for name in (\"cohort\", \"qualification_spec\", \"source_manifest\",\n        \"client_binary\", \"base_launcher\", \"host_launcher\")}\n    files.update({_open(canonical_ref), _open(inventory_ref), original.plan_receipt})\n"
            ],
            [
                "    for site in sites:\n        path = spec.workload_root / (site.workload_id + \".json\")\n        manifest = lanes._load(lanes._read(path))\n        resources = manifest[\"resources\"]\n        from urllib.parse import urlsplit\n        origins = sorted({f'{urlsplit(row[\"url\"]).scheme}://{urlsplit(row[\"url\"]).netloc}' for row in resources})\n",
                "    for site in sites:\n        path = spec.workload_root / (site.workload_id + \".json\")\n        manifest = lanes._load(lanes._read(path))\n        if fixed_front:\n            front_quick.native.validate_prepared(manifest)\n        resources = manifest[\"resources\"]\n        from urllib.parse import urlsplit\n        origins = sorted({f'{urlsplit(row[\"url\"]).scheme}://{urlsplit(row[\"url\"]).netloc}' for row in resources})\n"
            ],
            [
                "        \"formal_accepted_trace_count\": 0, \"scientific_credit\": False}\n    if selection is not None:\n        value.update(schema_version=2, artifact_type=MODE_CAPSULE_TYPE, mode_selection=selection)\n    if _context is not None:\n        for item in value[\"material_files\"]:\n            _open(item, _context)\n",
                "        \"formal_accepted_trace_count\": 0, \"scientific_credit\": False}\n    if selection is not None:\n        value.update(schema_version=2, artifact_type=MODE_CAPSULE_TYPE, mode_selection=selection)\n        if fixed_front:\n            value.update(schema_version=3, artifact_type=FRONT_CAPSULE_TYPE)\n    if _context is not None:\n        for item in value[\"material_files\"]:\n            _open(item, _context)\n"
            ],
            [
                "        \"original_canonical\", \"source_inventory\", \"source\", \"client_sha256\", \"sites\", \"graphs\", \"seed_payload\", \"material_files\",\n        \"material_modes\", \"permitted_slots\", \"archive_references\", \"class_target\", \"modes\", \"visits_per_class_mode\", \"formal_trace_target\", \"published_at\",\n        \"source_directory_modes\", \"reason\", \"formal_accepted_trace_count\", \"scientific_credit\"}\n    explicit_mode = value.get(\"artifact_type\") == MODE_CAPSULE_TYPE\n    if explicit_mode:\n        fields.add(\"mode_selection\")\n    if (set(value) != fields or not is_profile(value) or type(value.get(\"schema_version\")) is not int\n        or value[\"schema_version\"] != (2 if explicit_mode else 1) or value.get(\"contract\") != CONTRACT\n        or (value.get(\"class_target\"), value.get(\"visits_per_class_mode\"), value.get(\"formal_trace_target\")) != (50, 64, 16000)\n        or value.get(\"modes\") != list(rolling.plan.MODES) or value.get(\"scientific_credit\") is not False\n        or value.get(\"formal_accepted_trace_count\") != 0\n        or runtime is not None and value[\"runtime\"] != dict(runtime)\n        or not receipts._utc(value[\"published_at\"]) <= receipts._utc(before or receipts._now())):\n        raise ValueError(\"quick profile explicit prospective contract differs\")\n    for item in value[\"material_files\"]:\n        material = _open(item, _context)\n        if __import__(\"stat\").S_IMODE(material.stat().st_mode) != value[\"material_modes\"][str(material)]:\n            raise ValueError(\"quick profile current material permissions changed\")\n    source = lanes._load(lanes._read(Path(value[\"base_spec\"][\"source_manifest\"])))\n    if (source != value[\"source\"] or source.get(\"neqo_commit\") != NATIVE or source.get(\"neqo_pinned_commit\") != NATIVE\n        or source.get(\"lab_dirty\") is not False or source.get(\"neqo_dirty\") is not False\n        or source.get(\"lab_patch_sha256\") != EMPTY_SHA256 or source.get(\"neqo_patch_sha256\") != EMPTY_SHA256\n        or lanes._sha(lanes._read(Path(value[\"base_spec\"][\"client_binary\"]))) != value[\"client_sha256\"]):\n",
                "        \"original_canonical\", \"source_inventory\", \"source\", \"client_sha256\", \"sites\", \"graphs\", \"seed_payload\", \"material_files\",\n        \"material_modes\", \"permitted_slots\", \"archive_references\", \"class_target\", \"modes\", \"visits_per_class_mode\", \"formal_trace_target\", \"published_at\",\n        \"source_directory_modes\", \"reason\", \"formal_accepted_trace_count\", \"scientific_credit\"}\n    fixed_front = value.get(\"artifact_type\") == FRONT_CAPSULE_TYPE\n    explicit_mode = value.get(\"artifact_type\") in {MODE_CAPSULE_TYPE, FRONT_CAPSULE_TYPE}\n    if explicit_mode:\n        fields.add(\"mode_selection\")\n    if (set(value) != fields or not is_profile(value) or type(value.get(\"schema_version\")) is not int\n        or value[\"schema_version\"] != (3 if fixed_front else 2 if explicit_mode else 1) or value.get(\"contract\") != CONTRACT\n        or (value.get(\"class_target\"), value.get(\"visits_per_class_mode\"), value.get(\"formal_trace_target\")) != (50, 64, 16000)\n        or value.get(\"modes\") != list(rolling.plan.MODES) or value.get(\"scientific_credit\") is not False\n        or value.get(\"formal_accepted_trace_count\") != 0\n        or runtime is not None and value[\"runtime\"] != dict(runtime)\n        or not receipts._utc(value[\"published_at\"]) <= receipts._utc(before or receipts._now())):\n        raise ValueError(\"quick profile explicit prospective contract differs\")\n    if explicit_mode and (not isinstance(value[\"mode_selection\"], dict)\n            or set(value[\"mode_selection\"]) != {\"mode\", \"readiness\"}):\n        raise ValueError(\"quick explicit mode selection fields differ\")\n    selected_mode = value[\"mode_selection\"][\"mode\"] if explicit_mode else None\n    if front_quick.selected(value[\"seed_payload\"], selected_mode) != fixed_front:\n        raise ValueError(\"quick FRONT setting requires its distinct version-three profile\")\n    expected_native = front_quick.NATIVE if fixed_front else NATIVE\n    for item in value[\"material_files\"]:\n        material = _open(item, _context)\n        if __import__(\"stat\").S_IMODE(material.stat().st_mode) != value[\"material_modes\"][str(material)]:\n            raise ValueError(\"quick profile current material permissions changed\")\n    source = lanes._load(lanes._read(Path(value[\"base_spec\"][\"source_manifest\"])))\n    if (source != value[\"source\"] or source.get(\"neqo_commit\") != expected_native or source.get(\"neqo_pinned_commit\") != expected_native\n        or source.get(\"lab_dirty\") is not False or source.get(\"neqo_dirty\") is not False\n        or source.get(\"lab_patch_sha256\") != EMPTY_SHA256 or source.get(\"neqo_patch_sha256\") != EMPTY_SHA256\n        or lanes._sha(lanes._read(Path(value[\"base_spec\"][\"client_binary\"]))) != value[\"client_sha256\"]):\n"
            ],
            [
                "        raise ValueError(\"quick profile direct current installation fields disagree\")\n    inventory = lanes._load(lanes._read(_open(value[\"source_inventory\"], _context)))\n    source_root = Path(value[\"base_spec\"][\"runtime_source_root\"])\n    source_files = {str(source_root / name): item for name, item in inventory.items()}\n    materials = {item[\"path\"]: item for item in value[\"material_files\"]}\n    if (len(materials) != len(value[\"material_files\"]) or not source_files\n",
                "        raise ValueError(\"quick profile direct current installation fields disagree\")\n    inventory = lanes._load(lanes._read(_open(value[\"source_inventory\"], _context)))\n    source_root = Path(value[\"base_spec\"][\"runtime_source_root\"])\n    if fixed_front:\n        front_quick.validate_artifacts(value[\"runtime\"], context=_context)\n    source_files = {str(source_root / name): item for name, item in inventory.items()}\n    materials = {item[\"path\"]: item for item in value[\"material_files\"]}\n    if (len(materials) != len(value[\"material_files\"]) or not source_files\n"
            ],
            [
                "    for row in value[\"sites\"]:\n        manifest_path = Path(value[\"base_spec\"][\"workload_root\"]) / (row[\"workload_id\"] + \".json\")\n        manifest = lanes._load(lanes._read(manifest_path))\n        resources = manifest[\"resources\"]\n        graph = {\"resource_count\": len(resources), \"origins\": sorted({f'{urlsplit(item[\"url\"]).scheme}://{urlsplit(item[\"url\"]).netloc}' for item in resources}),\n            \"resources_sha256\": lanes._sha(lanes._json(resources))}\n",
                "    for row in value[\"sites\"]:\n        manifest_path = Path(value[\"base_spec\"][\"workload_root\"]) / (row[\"workload_id\"] + \".json\")\n        manifest = lanes._load(lanes._read(manifest_path))\n        if fixed_front:\n            front_quick.native.validate_prepared(manifest)\n        resources = manifest[\"resources\"]\n        graph = {\"resource_count\": len(resources), \"origins\": sorted({f'{urlsplit(item[\"url\"]).scheme}://{urlsplit(item[\"url\"]).netloc}' for item in resources}),\n            \"resources_sha256\": lanes._sha(lanes._json(resources))}\n"
            ],
            [
                "    if value[\"sites\"] != capsule[\"sites\"] or value[\"bindings\"] != capsule[\"seed_payload\"][\"bindings\"]:\n        raise ValueError(\"quick plan changed admitted site identities or immutable cohort bindings\")\n    seed = capsule[\"seed_payload\"]\n    mode = capsule[\"mode_selection\"][\"mode\"] if capsule[\"artifact_type\"] == MODE_CAPSULE_TYPE else seed[\"lanes\"][0][\"mode\"]\n    protected = {key: item for key, item in seed.items() if key in PLAN_FIELDS}\n    if (set(value) != set(protected) | {FIELD, \"scheduling\", \"sites\", \"readiness\", \"declared_at\", \"formal_accepted_trace_count\", \"scientific_credit\", \"planned_trace_count\", \"lanes\"}\n        or any(lanes._json(value[key]) != lanes._json(item) for key, item in protected.items())\n",
                "    if value[\"sites\"] != capsule[\"sites\"] or value[\"bindings\"] != capsule[\"seed_payload\"][\"bindings\"]:\n        raise ValueError(\"quick plan changed admitted site identities or immutable cohort bindings\")\n    seed = capsule[\"seed_payload\"]\n    mode = capsule[\"mode_selection\"][\"mode\"] if capsule[\"artifact_type\"] in {MODE_CAPSULE_TYPE, FRONT_CAPSULE_TYPE} else seed[\"lanes\"][0][\"mode\"]\n    protected = {key: item for key, item in seed.items() if key in PLAN_FIELDS}\n    if (set(value) != set(protected) | {FIELD, \"scheduling\", \"sites\", \"readiness\", \"declared_at\", \"formal_accepted_trace_count\", \"scientific_credit\", \"planned_trace_count\", \"lanes\"}\n        or any(lanes._json(value[key]) != lanes._json(item) for key, item in protected.items())\n"
            ],
            [
                "        or value[\"formal_accepted_trace_count\"] != 0 or value[\"scientific_credit\"] is not False):\n        raise ValueError(\"quick plan changed its frozen settings or explicit new-profile fields\")\n    sites = prepared_sites(value[\"sites\"])\n    allowed_modes = {mode} if capsule[\"artifact_type\"] == MODE_CAPSULE_TYPE else {row[\"mode\"] for row in seed[\"lanes\"]}\n    for row in value[\"lanes\"]:\n        lane = geometry.checked_lane({key: item for key, item in row.items() if key != \"campaign_sha256\"})\n        if lane.mode not in allowed_modes or tuple(lane.workload_ids) != tuple(site.workload_id for site in sites):\n            raise ValueError(\"quick plan changes its qualified setting or complete class set\")\n        if capsule[\"artifact_type\"] == MODE_CAPSULE_TYPE and not any(\n            row[\"mode\"] == mode and row[\"shard\"] == lane.shard\n            and set(lane.workload_ids) <= set(row[\"workload_ids\"]) for row in seed[\"lanes\"]):\n            raise ValueError(\"quick explicit mode plan changed its original class shard\")\n",
                "        or value[\"formal_accepted_trace_count\"] != 0 or value[\"scientific_credit\"] is not False):\n        raise ValueError(\"quick plan changed its frozen settings or explicit new-profile fields\")\n    sites = prepared_sites(value[\"sites\"])\n    allowed_modes = {mode} if capsule[\"artifact_type\"] in {MODE_CAPSULE_TYPE, FRONT_CAPSULE_TYPE} else {row[\"mode\"] for row in seed[\"lanes\"]}\n    for row in value[\"lanes\"]:\n        lane = geometry.checked_lane({key: item for key, item in row.items() if key != \"campaign_sha256\"})\n        if lane.mode not in allowed_modes or tuple(lane.workload_ids) != tuple(site.workload_id for site in sites):\n            raise ValueError(\"quick plan changes its qualified setting or complete class set\")\n        if capsule[\"artifact_type\"] in {MODE_CAPSULE_TYPE, FRONT_CAPSULE_TYPE} and not any(\n            row[\"mode\"] == mode and row[\"shard\"] == lane.shard\n            and set(lane.workload_ids) <= set(row[\"workload_ids\"]) for row in seed[\"lanes\"]):\n            raise ValueError(\"quick explicit mode plan changed its original class shard\")\n"
            ],
            [
                "    if not set(range(slot_start, slot_start + slot_count)) <= set(capsule[\"permitted_slots\"]):\n        raise ValueError(\"quick plan cannot expand the seed's declared remaining ledger\")\n    seed = capsule[\"seed_payload\"]\n    mode = capsule[\"mode_selection\"][\"mode\"] if capsule[\"artifact_type\"] == MODE_CAPSULE_TYPE else seed[\"lanes\"][0][\"mode\"]\n    if capsule[\"artifact_type\"] == CAPSULE_TYPE and any(row[\"mode\"] != mode for row in seed[\"lanes\"]):\n        raise ValueError(\"quick profile requires one independently ready fixed setting\")\n    sites = capsule[\"sites\"]\n",
                "    if not set(range(slot_start, slot_start + slot_count)) <= set(capsule[\"permitted_slots\"]):\n        raise ValueError(\"quick plan cannot expand the seed's declared remaining ledger\")\n    seed = capsule[\"seed_payload\"]\n    mode = capsule[\"mode_selection\"][\"mode\"] if capsule[\"artifact_type\"] in {MODE_CAPSULE_TYPE, FRONT_CAPSULE_TYPE} else seed[\"lanes\"][0][\"mode\"]\n    if capsule[\"artifact_type\"] == CAPSULE_TYPE and any(row[\"mode\"] != mode for row in seed[\"lanes\"]):\n        raise ValueError(\"quick profile requires one independently ready fixed setting\")\n    sites = capsule[\"sites\"]\n"
            ],
            [
                "    raw_campaign = geometry.render(lane, site_objects, static_capture_limits=value.get(\"capture_limits\"),\n        buflo_duration_policy=value.get(\"buflo_duration_policy\"), application_body_identity_policy=value.get(\"application_body_identity_policy\"),\n        qualification_delivery_compatibility=value.get(\"qualification_delivery_compatibility\"),\n        tamaraw_configuration_policy=value.get(\"tamaraw_configuration_policy\") if mode == \"tamaraw\" else None)\n    value[\"lanes\"] = [{**asdict(lane), \"campaign_sha256\": lanes._sha(raw_campaign)}]\n    campaign = spec.campaign_dir / (lane.campaign_name + \".yml\")\n    receipts.durable_create(campaign, raw_campaign)\n",
                "    raw_campaign = geometry.render(lane, site_objects, static_capture_limits=value.get(\"capture_limits\"),\n        buflo_duration_policy=value.get(\"buflo_duration_policy\"), application_body_identity_policy=value.get(\"application_body_identity_policy\"),\n        qualification_delivery_compatibility=value.get(\"qualification_delivery_compatibility\"),\n        tamaraw_configuration_policy=value.get(\"tamaraw_configuration_policy\") if mode == \"tamaraw\" else None,\n        front_configuration_policy=value.get(\"front_configuration_policy\") if mode == \"front\" else None,\n        front_incoming_credit_acceptance_policy=value.get(\"front_incoming_credit_acceptance_policy\") if mode == \"front\" else None)\n    value[\"lanes\"] = [{**asdict(lane), \"campaign_sha256\": lanes._sha(raw_campaign)}]\n    campaign = spec.campaign_dir / (lane.campaign_name + \".yml\")\n    receipts.durable_create(campaign, raw_campaign)\n"
            ]
        ]
    ],
    "mixed": [
        "3b0a8faf8afeb95c8deb8a8feb560214d0fc02e4655b20781776834bd00ba365",
        "fcb97be28badbe1379c7a1ae30030fcefa57143b947765065fd64688084e3a7c",
        [
            [
                "        raise ValueError('mixed historical reader differs after exact full-byte inverse')\n    if role == 'traffic' and before['sha256'] != old:\n        from . import rapid_quick_profile as quick\n        actual = fixed.reference(Path(quick.__file__))\n        fixed._open(actual)\n        if actual['sha256'] != '35808d483b82a4da1cd9c22e4a9ef967986dd7ab4ede448f8cd98db9d0c3b25c' or actual['mode'] != 0o644:\n            raise ValueError('mixed historical traffic quick dispatcher changed bytes/full mode')\n    return True\n\nRECEIPT = {'schema_version': 1, 'policy': BUFLO_POLICY, 'interval_us': 64000,\n",
                "        raise ValueError('mixed historical reader differs after exact full-byte inverse')\n    if role == 'traffic' and before['sha256'] != old:\n        from . import rapid_quick_profile as quick\n        from . import rapid_front_quick_compatibility as quick_front\n        actual = fixed.reference(Path(quick.__file__))\n        fixed._open(actual)\n        fixed._mixed_epoch()\n        quick_front.checked_dispatcher(actual)\n    return True\n\nRECEIPT = {'schema_version': 1, 'policy': BUFLO_POLICY, 'interval_us': 64000,\n"
            ],
            [
                "    for role in ('mixed', 'front_configuration', 'front_preparation', 'front_incoming_acceptance'):\n        fixed._open(value[role]); fixed._open(current[role])\n        if any(value[role][key] != current[role][key] for key in ('sha256', 'mode')):\n            raise ValueError('mixed epoch reader module bytes or full mode changed')\n    return [*value['base'].values(), *[value[role] for role in ('mixed', 'front_configuration', 'front_preparation', 'front_incoming_acceptance')]]\n\n",
                "    for role in ('mixed', 'front_configuration', 'front_preparation', 'front_incoming_acceptance'):\n        fixed._open(value[role]); fixed._open(current[role])\n        if any(value[role][key] != current[role][key] for key in ('sha256', 'mode')):\n            if role == 'mixed':\n                from . import rapid_front_quick_compatibility as quick_front\n                fixed._mixed_epoch()\n                if quick_front.compatible_mixed_module(value[role], current[role]):\n                    continue\n            raise ValueError('mixed epoch reader module bytes or full mode changed')\n    return [*value['base'].values(), *[value[role] for role in ('mixed', 'front_configuration', 'front_preparation', 'front_incoming_acceptance')]]\n\n"
            ]
        ]
    ]
}
_FRONT_HELPER_SHA256 = "37863d343522b7a59ac314873ee685ddc8b936f6915a59d8540cd140bde46816"


def restore(role, raw):
    """Restore the complete reviewed predecessor, including every scientific byte."""
    if role not in _PAIRS:
        raise ValueError("quick FRONT source role is outside the exact pair")
    before, after, edits = _PAIRS[role]
    digest = hashlib.sha256(raw).hexdigest()
    if digest == before:
        return raw
    if digest != after:
        raise ValueError("quick FRONT source is outside the exact whole-byte pair")
    for original, amended in edits:
        original, amended = original.encode(), amended.encode()
        if raw.count(amended) != 1:
            raise ValueError("quick FRONT inverse is absent or ambiguous")
        raw = raw.replace(amended, original, 1)
    if hashlib.sha256(raw).hexdigest() != before:
        raise ValueError("quick FRONT inverse changes protected predecessor bytes")
    return raw


def checked_dispatcher(reference):
    from . import rapid_fixed_condition_target as fixed
    from . import rapid_quick_profile as quick
    from . import rapid_front_quick_profile as front
    path = fixed._open(reference)
    if (path != Path(quick.__file__).absolute() or type(reference["mode"]) is not int
            or reference["mode"] != 0o644):
        raise ValueError("fixed target quick dispatcher Source or full mode changed")
    restore("quick", path.read_bytes())
    if reference["sha256"] == _PAIRS["quick"][1]:
        helper = fixed.reference(Path(front.__file__))
        fixed._open(helper)
        if (Path(front.__file__) != Path(quick.__file__).with_name("rapid_front_quick_profile.py")
                or type(helper["mode"]) is not int or helper["mode"] != 0o644
                or helper["sha256"] != _FRONT_HELPER_SHA256):
            raise ValueError("quick FRONT behavior helper Source or full mode changed")
    return True


def compatible_mixed_module(before, current):
    from . import rapid_fixed_condition_target as fixed
    from . import rapid_mixed_implementation_target as mixed
    old_path, new_path = fixed._open(before), fixed._open(current)
    if (before["sha256"], current["sha256"]) != tuple(_PAIRS["mixed"][:2]):
        return False
    if (new_path != Path(mixed.__file__).absolute() or type(before["mode"]) is not int
            or type(current["mode"]) is not int or before["mode"] != 0o644 or current["mode"] != 0o644):
        raise ValueError("mixed historical quick reader full mode differs")
    if restore("mixed", new_path.read_bytes()) != old_path.read_bytes():
        raise ValueError("mixed historical quick reader changes protected full bytes")
    return True
